# Generated by Django 3.2 on 2021-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='time_stamp',
            new_name='time',
        ),
    ]
