# Generated by Django 3.2 on 2021-05-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_time_stamp_client_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('alert', models.BooleanField(default=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
